name: Build StripeVCAM

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: cameronkatri/theos-docker:latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build package
      run: |
        make package FINALPACKAGE=1
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: StripeVCAMBypass.deb
        path: packages/*.deb
        if-no-files-found: error 