name: Build Custom VCAM

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Theos
      uses: Randomblock1/theos-action@v1
      with:
        theos-sdks: 'https://github.com/theos/sdks'
        theos-sdks-branch: 'master'
        
    - name: Build Custom VCAM
      run: |
        make clean
        make package FINALPACKAGE=1
        
    - name: Verify .deb structure
      run: |
        echo "=== Listing built packages ==="
        ls -la packages/
        
        echo "=== Extracting .deb to verify structure ==="
        cd packages
        DEB_FILE=$(ls *.deb | head -n1)
        echo "Processing: $DEB_FILE"
        
        mkdir -p extracted
        cd extracted
        ar -x "../$DEB_FILE"
        
        echo "=== .deb contents ==="
        ls -la
        
        echo "=== Extracting data.tar ==="
        if [ -f data.tar.xz ]; then
          tar -tf data.tar.xz
        elif [ -f data.tar.gz ]; then
          tar -tf data.tar.gz
        elif [ -f data.tar ]; then
          tar -tf data.tar
        fi
        
    - name: Upload .deb artifact
      uses: actions/upload-artifact@v4
      with:
        name: CustomVCAM-deb
        path: packages/*.deb
        retention-days: 30
        
    - name: Upload build logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: build-logs
        path: |
          .theos/obj/
          *.log
        retention-days: 7 