name: Build StripeVCAM

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      
    - name: Set up Theos
      uses: Randomblock1/theos-action@v1
      with:
        theos-sdks: 'https://github.com/theos/sdks'
        theos-sdks-branch: 'master'
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y fakeroot libtinfo-dev libz3-dev rsync curl perl unzip git libplist-utils
    
    - name: Build package
      run: |
        make package FINALPACKAGE=1
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: StripeVCAMBypass.deb
        path: packages/*.deb
        if-no-files-found: error 