name: Build CustomVCAM

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Setup Theos
      uses: Randomblock1/theos-action@v1
      with:
        theos-sdks: 'https://github.com/theos/sdks'
        theos-sdks-branch: 'master'
      
    - name: Verify Theos Installation
      run: |
        echo "Theos path: $THEOS"
        echo "Available SDKs:"
        ls -la $THEOS/sdks/ || echo "No SDKs directory found"
        echo "Theos version:"
        cat $THEOS/version || echo "No version file"
        
    - name: Check Available iOS SDKs
      run: |
        echo "Checking available iOS SDKs for iPhone 7 iOS 13.3.1 compatibility"
        cd $THEOS/sdks
        echo "Available iOS SDKs:"
        ls -la | grep iPhone || echo "No iPhone SDKs found"
        
        # Check specifically for iOS 13.x SDKs
        if ls | grep -q "iPhoneOS13"; then
          echo "✅ iOS 13.x SDKs found - perfect for iOS 13.3.1 target"
          ls | grep "iPhoneOS13"
        else
          echo "⚠️  No iOS 13.x SDKs found, will use latest available"
        fi
        
    - name: Build CustomVCAM
      run: |
        echo "Building CustomVCAM for iPhone 7 iOS 13.3.1"
        echo "Current directory: $(pwd)"
        echo "Available files:"
        ls -la
        echo "Theos environment:"
        echo "THEOS=$THEOS"
        echo "Available SDKs:"
        ls -la $THEOS/sdks/ | grep -i iphone || echo "No iPhone SDKs found"
        
        echo "Starting build process..."
        make clean || echo "Clean failed, continuing..."
        
        # Build with consistent target matching Makefile
        echo "Building with unified target: iphone:13.7:13.0"
        
        if ls $THEOS/sdks/ | grep -q "iPhoneOS13.7.sdk"; then
          echo "✅ Using iOS 13.7 SDK for iPhone 7 32-bit (checkra1n compatibility)"
          make package FINALPACKAGE=1 ARCHS="armv7" TARGET="iphone:13.7:13.0"
        elif ls $THEOS/sdks/ | grep -q "iPhoneOS13"; then
          SDK_VERSION=$(ls $THEOS/sdks/ | grep "iPhoneOS13" | head -1 | sed 's/iPhoneOS\([0-9.]*\)\.sdk/\1/')
          echo "✅ Using available iOS 13.x SDK for iPhone 7 32-bit: $SDK_VERSION"
          make package FINALPACKAGE=1 ARCHS="armv7" TARGET="iphone:${SDK_VERSION}:13.0"
        else
          echo "⚠️ Fallback to clang target for iPhone 7 32-bit"
          make package FINALPACKAGE=1 ARCHS="armv7" TARGET="iphone:clang:13.0"
        fi
        
        # Verify .deb package contents
        if [ -f packages/*.deb ]; then
          echo "✅ Package created successfully"
          echo "📦 Package contents:"
          ar -t packages/*.deb
          echo "📁 File listing:"
          dpkg-deb -c packages/*.deb | head -20
        else
          echo "❌ Package creation failed"
          exit 1
        fi
        
    - name: Upload .deb Package
      uses: actions/upload-artifact@v4
      with:
        name: CustomVCAM-${{ github.sha }}
        path: packages/*.deb
        retention-days: 30
        
    - name: Create Release (on tag)
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        files: packages/*.deb
        generate_release_notes: true
        title: CustomVCAM ${{ github.ref_name }}
        body: |
          ## CustomVCAM ${{ github.ref_name }}
          
          Virtual camera tweak for iPhone 7 iOS 13.3.1 (checkra1n)
          
          ### Installation
          1. Download the .deb file
          2. Transfer to your jailbroken device
          3. Install with: `dpkg -i CustomVCAM-*.deb`
          4. Respring your device
          
          ### Compatibility
          - iPhone 7 (ARM64)
          - iOS 13.3.1
          - checkra1n jailbreak
          - MobileSubstrate
          
          ### Features
          - System-wide camera hook
          - Web KYC bypass (Stripe, etc.)
          - Photo library injection
          - Overlay interface
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 