name: Build Custom VCAM v2

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

env:
  THEOS: /opt/theos

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        submodules: true
    
    - name: Cache Theos Installation
      uses: actions/cache@v4
      with:
        path: |
          /opt/theos
        key: theos-${{ runner.os }}-v2
        restore-keys: |
          theos-${{ runner.os }}-
    
    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git curl wget unzip fakeroot ldid
        
    - name: Install Theos
      run: |
        if [ ! -d "$THEOS" ]; then
          sudo git clone --recursive https://github.com/theos/theos.git $THEOS
          sudo chown -R $USER:$USER $THEOS
        fi
        
    - name: Download iOS Linux Toolchain
      run: |
        if [ ! -f "$THEOS/toolchain/linux/iphone/bin/clang" ]; then
          curl https://kabiroberai.com/toolchain/download.php?toolchain=ios-linux -Lo toolchain.tar.gz
          tar xzf toolchain.tar.gz -C $THEOS/toolchain
          rm toolchain.tar.gz
        fi
        
    - name: Download iOS 13.7 SDK
      run: |
        if [ ! -d "$THEOS/sdks/iPhoneOS13.7.sdk" ]; then
          curl -LO https://github.com/theos/sdks/archive/master.zip
          unzip master.zip
          cp -r sdks-master/iPhoneOS13.7.sdk $THEOS/sdks/
          rm -rf master.zip sdks-master
        fi
        
    - name: Validate Build Environment
      run: |
        echo "=== Environment Validation ==="
        echo "THEOS: $THEOS"
        echo "PATH: $PATH"
        
        echo "=== Theos Installation ==="
        ls -la $THEOS/ || echo "❌ Theos directory not found"
        
        echo "=== Toolchain Validation ==="
        ls -la $THEOS/toolchain/linux/iphone/bin/ || echo "❌ Toolchain not found"
        $THEOS/toolchain/linux/iphone/bin/clang --version || echo "❌ Clang not working"
        
        echo "=== SDK Validation ==="
        ls -la $THEOS/sdks/ || echo "❌ SDKs directory not found"
        ls -la $THEOS/sdks/iPhoneOS13.7.sdk/ || echo "❌ iOS 13.7 SDK not found"
        
        echo "=== Dependencies Validation ==="
        which ldid || echo "❌ ldid not found"
        which fakeroot || echo "❌ fakeroot not found"
        
        echo "=== Validation Complete ==="
        
    - name: Build Project
      env:
        PATH: ${{ env.THEOS }}/bin:${{ env.PATH }}
      run: |
        echo "=== Starting Build ==="
        make clean
        make package FINALPACKAGE=1
        echo "=== Build Complete ==="
        
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: CustomVCAM-${{ github.sha }}
        path: |
          packages/*.deb
          *.deb
        retention-days: 30
        
    - name: Create Release Assets
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      run: |
        mkdir -p release
        cp *.deb release/ 2>/dev/null || cp packages/*.deb release/ 2>/dev/null || echo "No .deb files found"
        ls -la release/
        
    - name: Generate Build Info
      run: |
        echo "## Build Information" > BUILD_INFO.md
        echo "- **Commit**: ${{ github.sha }}" >> BUILD_INFO.md
        echo "- **Branch**: ${{ github.ref_name }}" >> BUILD_INFO.md
        echo "- **Build Date**: $(date -u)" >> BUILD_INFO.md
        echo "- **Target Device**: iPhone 7 iOS 13.3.1 A1778" >> BUILD_INFO.md
        echo "- **Jailbreak**: checkra1n compatible" >> BUILD_INFO.md
        echo "" >> BUILD_INFO.md
        echo "## Installation" >> BUILD_INFO.md
        echo "1. Download the .deb file" >> BUILD_INFO.md
        echo "2. Transfer to your jailbroken device" >> BUILD_INFO.md
        echo "3. Install using Filza or dpkg" >> BUILD_INFO.md
        echo "4. Respring device" >> BUILD_INFO.md
        echo "5. Double-tap volume buttons to activate" >> BUILD_INFO.md
        
    - name: Upload Release Info
      uses: actions/upload-artifact@v4
      with:
        name: build-info-${{ github.sha }}
        path: BUILD_INFO.md 